#!/usr/bin/env node

var express = require('express'),
    app = express(),
    port = 8088;

var mapRoute = function(httpPath, fsPath) {
    app.use(httpPath, express.static(__dirname + '/' + fsPath));
};

mapRoute('/', '../src');
mapRoute('/cdn', '../dev/cdn');
mapRoute('/deps', '../deps');
mapRoute('/test', '../test');

app.listen(port);

console.log('Dev app running at http://localhost:' + port.toString() + '/index.html');
